In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('zomato.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur

- All Datatypes are correct.

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7105 entries, 0 to 7104
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           7105 non-null   int64
 1   Unnamed: 0             7105 non-null   int64
 2   restaurant name        7105 non-null   str
 3   restaurant type        7105 non-null   str
 4   rate (out of 5)        7037 non-null   float64
 5   num of ratings         7105 non-null   int64
 6   avg cost (two people)  7048 non-null   float64
 7   online_order           7105 non-null   str
 8   table booking          7105 non-null   str
 9   cuisines type          7105 non-null   str
 10  area                   7105 non-null   str
 11  local address          7105 non-null   str
dtypes: float64(2), int64(3), str(7)
memory usage: 666.2 KB

- Gives Row and Column Numbers

In [8]:
df.shape

(7105, 12)

In [9]:
df.isnull().sum()

Unnamed: 0.1              0
Unnamed: 0                0
restaurant name           0
restaurant type           0
rate (out of 5)          68
num of ratings            0
avg cost (two people)    57
online_order              0
table booking             0
cuisines type             0
area                      0
local address             0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['restaurant name'].duplicated().sum()

np.int64(0)

In [12]:
df['online_order'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [13]:
df['table booking'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [14]:
df['area'].unique()

<StringArray>
[                     'Bellandur', 'Byresandra,Tavarekere,Madiwala',
              'Bannerghatta Road',                   'Marathahalli',
                     'Whitefield',                   'Banashankari',
                    'Indiranagar',                'Electronic City',
               'Old Airport Road',                   'Basavanagudi',
                   'Malleshwaram',                   'Kalyan Nagar',
                    'Rajajinagar',                   'Brigade Road',
          'Koramangala 7th Block',                       'JP Nagar',
                   'Lavelle Road',                  'Sarjapur Road',
                            'HSR',                    'Frazer Town',
                   'Kammanahalli',                   'New BEL Road',
                      'Jayanagar',                    'Brookefield',
          'Koramangala 5th Block',          'Koramangala 4th Block',
          'Koramangala 6th Block',                  'Church Street',
                        'MG Road',                 'Residency Road']
Length: 30, dtype: str

In [15]:
df['local address'].unique()

<StringArray>
[                    'Bellandur',                           'HSR',
             'Bannerghatta Road',                  'Marathahalli',
                    'Whitefield',            'Kumaraswamy Layout',
              'Old Airport Road',         'Koramangala 5th Block',
                           'BTM',               'Electronic City',
                   'Indiranagar',         'Koramangala 3rd Block',
                      'JP Nagar',                  'Malleshwaram',
                  'Kammanahalli',                   'Rajajinagar',
                  'Basavanagudi',                 'Infantry Road',
                  'Kalyan Nagar',                 'Church Street',
                     'Jayanagar',               'Cunningham Road',
                 'Seshadripuram',                     'Banaswadi',
                 'Kaggadasapura',                 'Wilson Garden',
                  'Banashankari',              'Race Course Road',
         'Koramangala 6th Block',                'CV Raman Nagar',
                  'Brigade Road',                      'Nagawara',
                  'New BEL Road',         'Koramangala 1st Block',
                   'Brookefield',            'Jeevan Bhima Nagar',
                        'Hennur',            'Basaveshwara Nagar',
               'Kanakapura Road',                   'Yeshwantpur',
                       'Ejipura',                   'Frazer Town',
         'Koramangala 7th Block',                  'Bommanahalli',
                 'Sarjapur Road',                  'Thippasandra',
                  'Sanjay Nagar',                  'Shanti Nagar',
                      'RT Nagar',                  'Lavelle Road',
                        'Ulsoor',                   'Vijay Nagar',
                 'Vasanth Nagar',                'Sadashiv Nagar',
                   'City Market',                  'Shivajinagar',
                   'Magadi Road',                 'Richmond Road',
                'Residency Road',                   'Koramangala',
                        'Domlur',                'East Bangalore',
                    'HBR Layout',                     'Jalahalli',
                      'Majestic',                'St. Marks Road',
                       'MG Road',               'Rammurthy Nagar',
                      'KR Puram',               'South Bangalore',
         'Koramangala 4th Block',                    'Nagarbhavi',
             'Commercial Street',         'Koramangala 8th Block',
                'Sahakara Nagar',                        'Hebbal',
    'ITPL Main Road, Whitefield',                   'Mysore Road',
                   'Uttarahalli', 'Varthur Main Road, Whitefield',
                     'Yelahanka',                   'Sankey Road',
               'North Bangalore',               'Old Madras Road',
                    'Hosur Road',         'Koramangala 2nd Block',
                'West Bangalore',                        'Peenya',
                       'Kengeri',                 'Langford Town']
Length: 90, dtype: str

- Remove Unnamed Columns which have no use

In [16]:
df = df.drop(columns = ['Unnamed: 0.1','Unnamed: 0'])

df

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...
7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [18]:
df.isnull().sum()

restaurant name           0
restaurant type           0
rate (out of 5)          68
num of ratings            0
avg cost (two people)    57
online_order              0
table booking             0
cuisines type             0
area                      0
local address             0
dtype: int64

- To fill null placed by median

In [19]:
df['rate (out of 5)'] = df['rate (out of 5)'].fillna(df['rate (out of 5)'].median())
df['avg cost (two people)'] = df['avg cost (two people)'].fillna(df['avg cost (two people)'].median())

df

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...
7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [20]:
df.isnull().sum()

restaurant name          0
restaurant type          0
rate (out of 5)          0
num of ratings           0
avg cost (two people)    0
online_order             0
table booking            0
cuisines type            0
area                     0
local address            0
dtype: int64

In [21]:
df.describe()

       rate (out of 5)  num of ratings  avg cost (two people)
count      7105.000000     7105.000000            7105.000000
mean          3.514117      188.921042             539.161013
std           0.461028      592.171049             461.211329
min           1.800000        1.000000              40.000000
25%           3.200000       16.000000             300.000000
50%           3.500000       40.000000             400.000000
75%           3.800000      128.000000             600.000000
max           4.900000    16345.000000            6000.000000

- Want to fount outliers in num of ratings, avg cost (two people) and rate (out of 5).

- But These OUtliers are genuines.
   - For num of ratings, it can be possible.
   - For avg cost, it can also possible because for a luxury restaurant it may be high.
   - for rating, it also possible because for best restaurant we gave full rating also.

In [22]:
Q1 = df['num of ratings'].quantile(0.25)
Q3 = df['num of ratings'].quantile(0.75)

IQR = Q3-Q1

lower = Q1-(1.5*IQR)
upper = Q3+(1.5*IQR)

outliers = df[(df['num of ratings']<lower) | (df['num of ratings']>upper)]

outliers.head(5)

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
6,'@Italy,Casual Dining,4.1,305,700.0,Yes,No,Italian,Banashankari,Kumaraswamy Layout
11,Bar + Kitchen,"Bar, Casual Dining",4.4,2861,1500.0,No,Yes,"Continental, Asian, Italian, North Indian",Old Airport Road,Indiranagar
12,12th Main - Grand Mercure,Fine Dining,4.1,353,2000.0,No,Yes,"European, Asian","Byresandra,Tavarekere,Madiwala",Koramangala 3rd Block
14,The Pub,Pub,4.2,1731,1400.0,Yes,No,"Chinese, Continental, North Indian",Malleshwaram,Malleshwaram
15,Breakfast Club,Cafe,4.0,1509,900.0,Yes,Yes,"Cafe, Continental","Byresandra,Tavarekere,Madiwala",Koramangala 3rd Block

In [23]:
Q1 = df['avg cost (two people)'].quantile(0.25)
Q3 = df['avg cost (two people)'].quantile(0.75)

IQR = Q3-Q1

lower = Q1-(1.5*IQR)
upper = Q3+(1.5*IQR)

outliers = df[(df['avg cost (two people)']<lower) | (df['avg cost (two people)']>upper)]

outliers.head(5)

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
11,Bar + Kitchen,"Bar, Casual Dining",4.4,2861,1500.0,No,Yes,"Continental, Asian, Italian, North Indian",Old Airport Road,Indiranagar
12,12th Main - Grand Mercure,Fine Dining,4.1,353,2000.0,No,Yes,"European, Asian","Byresandra,Tavarekere,Madiwala",Koramangala 3rd Block
14,The Pub,Pub,4.2,1731,1400.0,Yes,No,"Chinese, Continental, North Indian",Malleshwaram,Malleshwaram
21,1Q1,"Casual Dining, Bar",4.3,595,2500.0,No,Yes,"Asian, Japanese, Thai, Malaysian, Vietnamese, ...",Brigade Road,Infantry Road
24,Char - Sterlings MAC Hotel,"Casual Dining, Bar",4.0,419,1400.0,Yes,Yes,"Chinese, Continental, North Indian, South Indi...",Indiranagar,Old Airport Road

In [24]:
Q1 = df['rate (out of 5)'].quantile(0.25)
Q3 = df['rate (out of 5)'].quantile(0.75)

IQR = Q3-Q1

lower = Q1-(1.5*IQR)
upper = Q3+(1.5*IQR)

outliers = df[(df['rate (out of 5)']<lower) | (df['rate (out of 5)']>upper)]

outliers.head(5)

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
231,Alibi - Maya International Hotel,Casual Dining,1.8,224,1200.0,No,No,"North Indian, Continental, Chinese",Brigade Road,Church Street
466,Asia Kitchen By Mainland China,"Casual Dining, Bar",4.9,2178,1500.0,Yes,Yes,"Asian, Chinese, Thai, Momos","Byresandra,Tavarekere,Madiwala",Koramangala 5th Block
527,Bageecha,Casual Dining,2.1,479,650.0,Yes,No,"North Indian, Chinese",Marathahalli,Marathahalli
607,Barbecue by Punjab Grill,Casual Dining,4.7,1316,1300.0,No,Yes,BBQ,Malleshwaram,Malleshwaram
668,Belgian Waffle Factory,Dessert Parlor,4.8,186,400.0,Yes,No,Desserts,"Byresandra,Tavarekere,Madiwala",Koramangala 5th Block

In [25]:
df.head(5)

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur

In [28]:
import re



# Function to clean restaurant names
def clean_restaurant_name(name):

    if pd.isna(name):
        return name

    name = str(name)

    # 1. Fix encoding / mojibake
    for _ in range(3):
        try:
            fixed = name.encode("latin1").decode("utf-8")
            if fixed == name:
                break
            name = fixed
        except (UnicodeEncodeError, UnicodeDecodeError):
            break

    # 2. Remove leading/trailing spaces
    name = name.strip()

    # 3. Remove unwanted symbols from beginning
    # Example: #FeelTheROLL -> FeelTheROLL
    # '@ Biryani Central -> Biryani Central
    name = re.sub(r"^[#@'\"]+\s*", "", name)

    # 4. Remove unnecessary special characters from beginning/end
    name = re.sub(r"^[^A-Za-z0-9]+", "", name)
    name = re.sub(r"[^A-Za-z0-9À-ÿ&'().,+\- ]+$", "", name)

    # 5. Replace multiple spaces with one
    name = re.sub(r"\s+", " ", name)

    # 6. Remove spaces before punctuation
    name = re.sub(r"\s+([,.)])", r"\1", name)

    # 7. Remove spaces after opening brackets
    name = re.sub(r"([\(])\s+", r"\1", name)

    return name.strip()


# Apply cleaning
df["restaurant name"] = df["restaurant name"].apply(clean_restaurant_name)

# Check results
df.head(20)

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
5,99,"Takeaway, Delivery",3.4,37,200.0,No,No,"Mughlai, Biryani, Chinese, North Indian",Whitefield,Whitefield
6,Italy,Casual Dining,4.1,305,700.0,Yes,No,Italian,Banashankari,Kumaraswamy Layout
7,North Parontha Hut,"Takeaway, Delivery",2.8,40,300.0,No,No,North Indian,Indiranagar,Old Airport Road
8,B.C,Quick Bites,3.2,49,300.0,Yes,No,"Arabian, Sandwich, Rolls, Burger","Byresandra,Tavarekere,Madiwala",Koramangala 5th Block
9,100°C,Casual Dining,3.7,41,450.0,No,No,"Biryani, North Indian","Byresandra,Tavarekere,Madiwala",BTM
10,to 11 Express Biriyanis,Quick Bites,3.5,22,300.0,Yes,No,"Biryani, Kebab",Electronic City,Electronic City
11,Bar + Kitchen,"Bar, Casual Dining",4.4,2861,1500.0,No,Yes,"Continental, Asian, Italian, North Indian",Old Airport Road,Indiranagar
12,12th Main - Grand Mercure,Fine Dining,4.1,353,2000.0,No,Yes,"European, Asian","Byresandra,Tavarekere,Madiwala",Koramangala 3rd Block
13,Pizzeria,Casual Dining,4.1,119,800.0,Yes,No,"Pizza, Salad",Basavanagudi,JP Nagar
14,The Pub,Pub,4.2,1731,1400.0,Yes,No,"Chinese, Continental, North Indian",Malleshwaram,Malleshwaram
15,Breakfast Club,Cafe,4.0,1509,900.0,Yes,Yes,"Cafe, Continental","Byresandra,Tavarekere,Madiwala",Koramangala 3rd Block
16,Urban Bistro,Casual Dining,4.1,218,600.0,Yes,Yes,"North Indian, Chinese, Fast Food, Biryani","Byresandra,Tavarekere,Madiwala",Koramangala 5th Block
17,Ice Cafe,Cafe,3.5,24,550.0,No,No,"Cafe, Fast Food, Chinese, Beverages",Kalyan Nagar,Kammanahalli
18,1947,Casual Dining,3.9,620,1000.0,No,Yes,"North Indian, Chinese, Continental",Rajajinagar,Rajajinagar
19,Games Cafe,Cafe,3.4,58,400.0,Yes,No,"Cafe, Fast Food",Banashankari,Basavanagudi